### ISSUE TITLE
Cannot connect to a VM Postgres through pgbouncer-k8s

### ISSUE THREAD

**Issue by mertalpt** [canonical/pgbouncer-k8s-operator#122]
## Steps to reproduce
```
# This is not the exact order I used but it should get you to my state, I lost the steps and cannot retrace my steps at the moment
# Expect: lxd controller named lxd-local with a model named collectivedb
# Expect: microk8s controller named microk8s with a model named collectivedb-k8s
juju switch lxd-local:collectivedb
juju deploy postgresql --channel 14/edge -n 2
juju deploy data-integrator --channel edge
juju offer postgresql:database

juju switch microk8s:collectivedb-k8s
juju deploy pgbouncer-k8s --channel 1/edge
juju consume lxd-local:admin/collectivedb.postgresql
juju relate pgbouncer-k8s lxd-local:admin/collectivedb.postgresql
juju offer pgbouncer-k8s database

juju switch lxd-local:collectivedb
juju consume microk8s:admin/collectivedb-k8s.pgbouncer-k8s
juju relate data-integrator microk8s:admin/collectivedb-k8s.pgbouncer-k8s
juju config data-integrator database_name=test
juju run-action data-integrator get-credentials --wait

# This returns service name for the pod for the hostname, which does not work
# So, I get the pod IP from microk8s, which works slightly better
psql -h 10.x.x.x -p 6432 -U <uname> -d test
# First time around this gave an error about a query timeout, I lost the message
# Then, I went into the pgbouncer container to debug and I could psql to the database from there
# I can also psql from local machine
# After some poking and prodding the psql command above started failing to find pgbouncer
psql: error: connection to server at "10.1.218.78", port 6432 failed: Invalid argument
	Is the server running on that host and accepting TCP/IP connections?
```

## Expected behavior
I expect to be able to connect to `pgbouncer` via Postgres client software.

## Actual behavior
I get query timeouts or invalid argument errors as described in the reproduction steps.

## Versions

Operating system: Ubuntu 22.04.2 LTS

Juju CLI: 2.9.44-ubuntu-amd64

Juju agent: 2.9.42

postgresql charm revision: 312
pgbouncer-k8s charm revision: 61

microk8s: MicroK8s v1.27.4 revision 5643

## Log output

Juju debug log: 
```
unit-pgbouncer-k8s-0: 14:05:37 ERROR juju.worker.uniter.operation hook "pgbouncer-pebble-ready" (via hook dispatching script: dispatch) failed: exit status 1
unit-pgbouncer-k8s-0: 14:05:37 ERROR juju.worker.uniter pebble poll failed for container "pgbouncer": failed to send pebble-ready event: hook failed
unit-pgbouncer-k8s-0: 14:05:44 ERROR unit.pgbouncer-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 660, in <module>
    main(PgBouncerK8sCharm)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/./src/charm.py", line 189, in _on_pgbouncer_pebble_ready
    container.replan()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/model.py", line 1915, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 1680, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-pgbouncer-k8s-0/charm/venv/ops/pebble.py", line 1761, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "metrics_server" (cannot start service: exited quickly with code 1)
----- Logs from task 0 -----
2023-08-04T11:05:40Z INFO Service "pgbouncer_0" already started.
----- Logs from task 1 -----
2023-08-04T11:05:40Z INFO Service "pgbouncer_1" already started.
----- Logs from task 2 -----
2023-08-04T11:05:40Z INFO Service "pgbouncer_2" already started.
----- Logs from task 3 -----
2023-08-04T11:05:41Z INFO Service "pgbouncer_3" already started.
----- Logs from task 4 -----
2023-08-04T11:05:41Z INFO Service "pgbouncer_4" already started.
----- Logs from task 5 -----
2023-08-04T11:05:41Z INFO Service "pgbouncer_5" already started.
----- Logs from task 6 -----
2023-08-04T11:05:42Z INFO Service "pgbouncer_6" already started.
----- Logs from task 7 -----
2023-08-04T11:05:42Z INFO Service "pgbouncer_7" already started.
----- Logs from task 9 -----
2023-08-04T11:05:43Z INFO Most recent service output:
    ts=2023-08-04T11:05:43.783Z caller=collector.go:138 level=error msg="error setting up DB connection" err="error pinging pgbouncer: pq: password authentication failed"
2023-08-04T11:05:43Z ERROR cannot start service: exited quickly with code 1
```

# Additional Info
[Pastebin](https://pastebin.canonical.com/p/CcsygQ9bSh/) with some more information.

**Comment by dragomirp** [comment]
Hi, sounds related to https://github.com/canonical/postgresql-operator/issues/197. Can you retry using the workaround to open the ports mentioned there?

**Comment by mertalpt** [comment]
Not sure if I did it correctly but it did not work.
```
### Actions
$ juju run --unit postgresql/0 open-port 5432/tcp
$ psql -h 10.1.218.114 -p 6432 -U relation_id_2 -d test
psql: error: connection to server at "10.1.218.114", port 6432 failed: FATAL:  query_wait_timeout

# 10.1.218.114 is the IP of the pod running pgbouncer-k8s

### juju debug-log --replay
...
controller-0: 15:42:37 ERROR juju.worker.remoterelations cmr error in remote application worker for pgbouncer-k8s: opening facade to remote model: cannot resolve "controller-service.controller-microk8s.svc.cluster.local": lookup controller-service.controller-microk8s.svc.cluster.local on 127.0.0.53:53: server misbehaving
controller-0: 15:42:53 ERROR juju.worker.remoterelations cmr error in remote application worker for pgbouncer-k8s: opening facade to remote model: cannot resolve "controller-service.controller-microk8s.svc.cluster.local": lookup controller-service.controller-microk8s.svc.cluster.local on 127.0.0.53:53: server misbehaving
unit-postgresql-0: 15:43:07 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-postgresql-0: 15:43:07 ERROR unit.postgresql/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 338, in list_users
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 107, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "None" to address: Temporary failure in name resolution


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1226, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/main.py", line 439, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 843, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/venv/ops/framework.py", line 922, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 799, in _on_start
    self._start_primary(event)
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 833, in _start_primary
    users = self.postgresql.list_users()
  File "/var/lib/juju/agents/unit-postgresql-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 344, in list_users
    raise PostgreSQLListUsersError()
charms.postgresql_k8s.v0.postgresql.PostgreSQLListUsersError
unit-postgresql-0: 15:43:07 ERROR juju.worker.uniter.operation hook "start" (via hook dispatching script: dispatch) failed: exit status 1
...
```

**Comment by marceloneppel** [comment]
@mertalpt, I'm still trying to publish the new revision. I'm gonna update you here and on MM when it's done.

**Comment by marceloneppel** [comment]
@mertalpt, revision 63 has the fix for this issue.
